### ISSUE TITLE
Allow AmazonSQS client to be more configurable

### ISSUE THREAD

**Issue by jhovell** [Nordstrom/kafka-connect-sqs#20]
Seems somewhat related to [this issue](https://github.com/Nordstrom/kafka-connect-sqs/issues/19). 

It would be useful to be able to provide a provider class for the entire `AmazonSQS` client object to allow for a host of configuration issues rather than just the credentials provider class today.

My use case is to provide an endpoint configuration to use for local testing but I'm sure there are countless others (eg enabling SDK metrics). Examples of custom client configuration is here

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/creating-clients.html

Perhaps this project could include an interface such as the following and allow for users to provide a class that implements the interface. `config` is the Kafka Connect name/value pairs config map, so that the client could be created based on client config and not have to rely on system properties or environment variables that might not be settable if using a hosted Kafka Connect such as MSK Connect.
 
```java
public interface AmazonSQSProvider {
   AmazonSQS provide(Map<String, String> config);
}
```

**Comment by jhovell** [comment]
Happy to provide a contrib/PR for this btw

**Comment by rajki** [comment]
Hey folks, chiming in with a PR here. It's not a full fledged solution described in the OP, but I've had the need to override the endpoint configuration as well, so the patch contains those changes.

**Comment by dylanmei** [comment]
To my knowledge, there's no issues running the connector with MSK Connect. See #31

The idea of a generic client provider is interesting.
