### ISSUE TITLE
SQS connector doesn't work without AWS_REGION env variable.

### ISSUE THREAD

**Issue by peterehik-px** [Nordstrom/kafka-connect-sqs#22]
Hi, so I was trying to run the source connector in MSK connect and kept getting errors when trying to connect because it couldn't figure out what region my SQS queue was in. When using MSK connect, we can only set the worker/connector configurations, there's no way to set environment variables so I created this PR to allow the user to set the sqs region using a connector configuration. 

I've tested this out locally to make sure it works and it does. This connector doesn't work on MSK connect when using IAM auth but it's not because of anything wrong with the connector, MSK connect is just weird and buggy. I created a support ticket with AWS like 3 days ago and they can't figure out why the connector doesn't work. The issue has to do with the plugin classloader, my guess is they put the aws-iam-auth jar in the plugin path instead of in the kafka/libs folder or some other classspath. It's a known issue: https://github.com/aws/aws-msk-iam-auth/issues/11/  

Anyway as soon as I brought up a local kafka connect instance, it worked perfectly with IAM auth, I was able to connect to sqs and sink messages to my kafka topic. 

Thanks y'all for making this open source, it's been super helpful to me already.

Here's my PR: https://github.com/Nordstrom/kafka-connect-sqs/pull/21/files

**Comment by dylanmei** [comment]
PR merged and released with [v1.4.0](https://github.com/Nordstrom/kafka-connect-sqs/releases/tag/v1.4.0)
