### ISSUE TITLE
SQS connectors are not getting installed (docker-compose.yml)

### ISSUE THREAD

**Issue by twoi** [Nordstrom/kafka-connect-sqs#26]
After doing `mvn clean package`, the `target/plugins` folder is empty. but the `connect` container in `docker-compose.yml` sets up this volume:
```
     - ./target/plugin:/opt/connectors
```
Removing `/plugin` fixes the problem.

**Comment by dylanmei** [comment]
Thank you for your note. This was addressed with PR #28
