### ISSUE TITLE
Timeout error on Source

### ISSUE THREAD

**Issue by valmoz** [Nordstrom/kafka-connect-sqs#36]
We're currently using the connector from AWS MSK.
While executing the load test, we encountered the following error:

```
WorkerSourceTask{id=test-1-5-7-0} flushing 7423 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:502)

WorkerSourceTask{id=test-1-5-7-0} Failed to flush, timed out while waiting for producer to flush outstanding 6365 messages (org.apache.kafka.connect.runtime.WorkerSourceTask:509)

WorkerSourceTask{id=test-1-5-7-0} Failed to commit offsets (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:116)

```
Is there some config that we could apply to avoid this issue? or is it something related to the config of the MSK cluster?

Thanks
Mauro

**Comment by valmoz** [comment]
@dylanmei sorry to disturb you, do you have some suggestions?

**Comment by dylanmei** [comment]
I'm unclear given the amount of information here. If you think it correlates to your load test, try configurations that limit the amount of data in flight at once. If you think it correlates to MSK, check that you can reach the system and its IAM policy allows writes.

**Comment by dylanmei** [comment]
Closing stale issue.
