### ISSUE TITLE
Missing required configuration "sqs.endpoint.url" which has no default value on v1.5.0

### ISSUE THREAD

**Issue by tfpereira** [Nordstrom/kafka-connect-sqs#37]
Hey,

I'm getting this error on version v1.5.0 when creating a source connector but according to the docs its supposed to be optional. My configuration is pretty much the one on the README file. Any ideas?

**Comment by tfpereira** [comment]
I did find that MR afterwards and ended up moving forward with v1.4.0 since I didn't really need the features that v1.5.0 brought forward - everything worked ok with v1.4.0

**Comment by dylanmei** [comment]
Closing this as it's handled by #33. Let us know how v1.5.0 goes for you.

**Comment by calvin-barelds** [comment]
Also faced this issue when upgrading our connector, it's not a great migration path currently as now we need to add an extra parameter on each connector configuration. Can we either please update the documentation to reflect this is mandatory or make this optional?

Currently, passing an empty string does work, but as mentioned, it's not great.

**Comment by dylanmei** [comment]
You should find that `sqs.endpoint.url` is truly optional in release v1.6.2.
