### ISSUE TITLE
NoClassDefFoundError for SqsSourceConnectorConfig running on AWS

### ISSUE THREAD

**Issue by gytisjakutonis-visma** [Nordstrom/kafka-connect-sqs#55]
Source Connector running on AWS

Build from source code with Corretto-11.0.20.9.1
Running on MSK with Corretto-11.0.20.9.1

CloudWatch log:
[Worker-0af43a3182ee8e7e0] Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.nordstrom.kafka.connect.sqs.SqsSourceConnectorConfig

at com.nordstrom.kafka.connect.sqs.SqsSourceConnector.config(SqsSourceConnector.java:100)

**Comment by gytisjakutonis-visma** [comment]
connector config:
connector.class=com.nordstrom.kafka.connect.sqs.SqsSourceConnector
tasks.max=2
topics=Upload
value.converter=org.apache.kafka.connect.storage.StringConverter
sqs.queue.url=...
key.converter=org.apache.kafka.connect.storage.StringConverter

**Comment by dylanmei** [comment]
Use the latest [1.6.2 release](https://github.com/Nordstrom/kafka-connect-sqs/releases/tag/v1.6.2) if you're having difficulties building from source.

**Comment by gytisjakutonis-visma** [comment]
that solved the issue, thanks!
